/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.takeaway.challenge.controller;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Department;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.annotation.Generated;
import javax.validation.Valid;
@Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-12-03T00:57:40.657Z")

@Api(value = "departments", description = "the department API")
@RequestMapping(value = "/v1")
public interface DepartmentApi {

    @ApiOperation(value = "Add a new department", nickname = "addDepartment", notes = "", tags={ "departments", })
    @ApiResponses(value = { @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/departments",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addDepartment(@ApiParam(value = "Department object that needs to be added to the system" ,required=true )  @Valid @RequestBody Department body);

}
